version: '3'

services:
  #server
  laravel-server:
    build: ./conf
    image: laravel-server
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./:/var/www/html

  #mysql
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db-data:/var/lib/mysql:cached

  mysql-test:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=testing

  #nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:8000"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - laravel-server

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

  #redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db-data:
